"""creacion inicial

Revision ID: ae6a5cd9f7ef
Revises: 
Create Date: 2026-06-28 14:42:33.624057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a5cd9f7ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infidelity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('historia', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_media', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('infidelity_id', sa.UUID(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('comentario_datetime', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['infidelity_id'], ['infidelity.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infidelity_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('infidelity_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['infidelity_id'], ['infidelity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infidelity_photos')
    op.drop_table('comments')
    op.drop_table('social_media')
    op.drop_table('infidelity')
    op.drop_table('users')
    # ### end Alembic commands ###
