"""remove infidelity_id from comments

Revision ID: b3e9521712cd
Revises: ae6a5cd9f7ef
Create Date: 2026-06-29 22:43:18.458552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e9521712cd'
down_revision: Union[str, Sequence[str], None] = 'ae6a5cd9f7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_infidelity_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'infidelity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('infidelity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_infidelity_id_fkey'), 'comments', 'infidelity', ['infidelity_id'], ['id'])
    # ### end Alembic commands ###
